apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchard-chart.fullname" . }}-secrets
  labels:
    {{- include "orchard-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ include "orchard-chart.connectionString" . | quote }}
  admin-password: {{ required "tenant.adminPassword must be set" .Values.tenant.adminPassword | quote }}
