tenant:
  name: "SiteC"
  recipe: "Agency"
  adminPassword: "StrongPassword123!"
  connectionString: "Server=tcp:your-db.database.windows.net;Database=AlphaDB;User ID=admin;Password=..."

service:
  type: LoadBalancer