image:
  repository: example654.azurecr.io/orchard
  tag: "latest" 
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: LoadBalancer
  port: 80

# Placeholders that each site instance will override
tenant:
  name: "default"
  recipe: "Core"
  connectionString: ""
  adminPassword: ""

#ingress:
#  enabled: true
#  className: "nginx"
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#  host: "placeholder.com"